import { OccasionType } from "@prochar/shared";

export interface RawSeedTemplate {
  slug: string;
  title: string;
  titleEn: string;
  occasionType: OccasionType;
  isActive: boolean;
  layoutConfig: Record<string, unknown>;
}

export const SEED_TEMPLATES_DATA: RawSeedTemplate[] = [
  // §4. Template 1 — Victory Day (বিজয় দিবস)
  {
    slug: "victory-day-classic",
    title: "বিজয় দিবস — ক্লাসিক",
    titleEn: "Victory Day — Classic",
    occasionType: "victory_day",
    isActive: true,
    layoutConfig: {
      schemaVersion: 1,
      canvas: { width: 600, height: 800 },
      layoutFamily: "triple-top",
      colorScheme: {
        background: "#FFF8E7",
        primary: "#006A4E",
        secondary: "#D61F31",
        accent: "#F7C948",
        textOnPrimary: "#FFFFFF",
        textOnLight: "#1A1A1A",
      },
      contrastPairs: [
        { fg: "textOnPrimary", bg: "primary", min: 4.5 },
        { fg: "textOnPrimary", bg: "secondary", min: 4.5 },
        { fg: "textOnLight", bg: "background", min: 4.5 },
      ],
      layers: [
        { id: "base", type: "rect", x: 0, y: 0, w: 600, h: 800, fill: "$background" },
        { id: "top-band", type: "rect", x: 0, y: 0, w: 600, h: 280, fill: "$primary" },
        { id: "headline-block", type: "rect", x: 0, y: 280, w: 600, h: 170, fill: "$secondary" },
      ],
      photoSlots: [
        { id: "center", shape: "arch", x: 215, y: 36, w: 170, h: 214, z: 4, border: { width: 4, color: "$accent" } },
        { id: "left", shape: "rounded", x: 36, y: 76, w: 150, h: 174, z: 3, radius: 6, border: { width: 4, color: "$accent" } },
        { id: "right", shape: "rounded", x: 414, y: 76, w: 150, h: 174, z: 3, radius: 6, border: { width: 4, color: "$accent" } },
        { id: "pairLeft", shape: "rounded", x: 95, y: 50, w: 190, h: 200, z: 3, radius: 6, border: { width: 4, color: "$accent" } },
        { id: "pairRight", shape: "rounded", x: 315, y: 50, w: 190, h: 200, z: 3, radius: 6, border: { width: 4, color: "$accent" } },
      ],
      photoAssignment: {
        "1": ["center"],
        "2": ["pairLeft", "pairRight"],
        "3": ["center", "left", "right"],
      },
      textSlots: [
        {
          id: "headline",
          source: "headline",
          x: 30,
          y: 290,
          w: 540,
          h: 150,
          fontFamily: "Hind Siliguri",
          fontWeight: 700,
          minFont: 30,
          maxFont: 88,
          maxLines: 3,
          lineHeight: 1.3,
          align: "center",
          valign: "middle",
          color: "$textOnPrimary",
        },
        {
          id: "subtext",
          source: "subtext",
          x: 60,
          y: 462,
          w: 480,
          h: 64,
          fontFamily: "Noto Sans Bengali",
          fontWeight: 500,
          minFont: 14,
          maxFont: 24,
          maxLines: 2,
          lineHeight: 1.5,
          align: "center",
          valign: "middle",
          color: "$textOnLight",
          truncate: true,
        },
      ],
      footer: { preset: "standard-v1", fill: "$primary", topRule: { height: 4, color: "$accent" } },
      decorations: [
        {
          key: "sunburst_rays",
          asset: "victory-day-classic/sunburst_rays.svg",
          layer: "bg",
          opacity: 0.18,
          minIntensity: "high",
          placements: [{ x: 0, y: 0, w: 600, h: 280 }],
        },
        {
          key: "paddy",
          asset: "victory-day-classic/paddy.svg",
          layer: "bg",
          opacity: 1,
          minIntensity: "low",
          placements: [{ x: 0, y: 600, w: 600, h: 100 }],
        },
        {
          key: "doves",
          asset: "victory-day-classic/doves.svg",
          layer: "mid",
          opacity: 1,
          minIntensity: "medium",
          placements: [{ x: 360, y: 540, w: 200, h: 80 }],
        },
        {
          key: "flag_wave",
          asset: "victory-day-classic/flag_wave.svg",
          layer: "mid",
          opacity: 1,
          minIntensity: "medium",
          placements: [{ x: 40, y: 536, w: 150, h: 96 }],
        },
        {
          key: "floral_border_a",
          asset: "victory-day-classic/floral_border_a.svg",
          layer: "fg",
          opacity: 1,
          minIntensity: "low",
          placements: [{ x: 0, y: 0, w: 600, h: 700 }],
        },
      ],
      aiAllowedDecorations: ["sunburst_rays", "paddy", "doves", "flag_wave", "floral_border_a"],
      maxPhotos: 3,
    },
  },

  // §5.1 Template 2 — Condolence / Tribute (শোক ও স্মরণ)
  {
    slug: "condolence-tribute",
    title: "শোক ও স্মরণ — শ্রদ্ধাঞ্জলি",
    titleEn: "Condolence — Tribute",
    occasionType: "condolence",
    isActive: true,
    layoutConfig: {
      schemaVersion: 1,
      canvas: { width: 600, height: 800 },
      layoutFamily: "memorial-arch",
      colorScheme: {
        background: "#F2EFE8",
        primary: "#1C1C1C",
        secondary: "#6B6B6B",
        accent: "#9A8B5A",
        textOnPrimary: "#F7F5F0",
        textOnLight: "#1C1C1C",
      },
      contrastPairs: [
        { fg: "textOnPrimary", bg: "primary", min: 4.5 },
        { fg: "textOnLight", bg: "background", min: 4.5 },
      ],
      layers: [
        { id: "base", type: "rect", x: 0, y: 0, w: 600, h: 800, fill: "$background" },
        { id: "frame-outer", type: "frame", x: 14, y: 14, w: 572, h: 672, stroke: { width: 10, color: "$primary" } },
        { id: "frame-inner", type: "frame", x: 34, y: 34, w: 532, h: 632, stroke: { width: 1.5, color: "$secondary" } },
      ],
      photoSlots: [
        { id: "center", shape: "arch", x: 185, y: 70, w: 230, h: 290, z: 4, border: { width: 5, color: "$accent" }, filter: "grayscale(0.85)" },
        { id: "left", shape: "circle", x: 40, y: 190, w: 120, h: 120, z: 3, border: { width: 4, color: "$accent" }, filter: "grayscale(0.85)" },
        { id: "right", shape: "circle", x: 440, y: 190, w: 120, h: 120, z: 3, border: { width: 4, color: "$accent" }, filter: "grayscale(0.85)" },
        { id: "pairLeft", shape: "arch", x: 70, y: 90, w: 210, h: 270, z: 3, border: { width: 5, color: "$accent" }, filter: "grayscale(0.85)" },
        { id: "pairRight", shape: "arch", x: 320, y: 90, w: 210, h: 270, z: 3, border: { width: 5, color: "$accent" }, filter: "grayscale(0.85)" },
      ],
      photoAssignment: {
        "1": ["center"],
        "2": ["pairLeft", "pairRight"],
        "3": ["center", "left", "right"],
      },
      textSlots: [
        {
          id: "headline",
          source: "headline",
          x: 50,
          y: 464,
          w: 500,
          h: 116,
          fontFamily: "Tiro Bangla",
          fontWeight: 400,
          minFont: 28,
          maxFont: 64,
          maxLines: 3,
          lineHeight: 1.3,
          align: "center",
          valign: "middle",
          color: "$textOnLight",
        },
        {
          id: "subtext",
          source: "subtext",
          x: 90,
          y: 586,
          w: 420,
          h: 68,
          fontFamily: "Noto Serif Bengali",
          fontWeight: 400,
          minFont: 14,
          maxFont: 22,
          maxLines: 3,
          lineHeight: 1.5,
          align: "center",
          valign: "top",
          color: "$textOnLight",
          truncate: true,
        },
      ],
      footer: { preset: "standard-v1", fill: "$primary", topRule: { height: 3, color: "$accent" } },
      decorations: [
        {
          key: "corner_ornament",
          asset: "condolence-tribute/corner_ornament.svg",
          layer: "fg",
          opacity: 1,
          minIntensity: "low",
          placements: [
            { x: 22, y: 22, w: 56, h: 56 },
            { x: 522, y: 22, w: 56, h: 56, flipX: true },
            { x: 22, y: 630, w: 56, h: 56, flipY: true },
            { x: 522, y: 630, w: 56, h: 56, flipX: true, flipY: true },
          ],
        },
        {
          key: "dove_single",
          asset: "condolence-tribute/dove_single.svg",
          layer: "mid",
          opacity: 1,
          minIntensity: "low",
          placements: [{ x: 254, y: 372, w: 92, h: 74 }],
        },
        {
          key: "divider_line",
          asset: "condolence-tribute/divider_line.svg",
          layer: "mid",
          opacity: 1,
          minIntensity: "medium",
          placements: [{ x: 200, y: 452, w: 200, h: 8 }],
        },
      ],
      aiAllowedDecorations: ["corner_ornament", "dove_single", "divider_line"],
      maxPhotos: 3,
    },
  },

  // §5.2 Template 3 — Campaign (নির্বাচনী প্রচার)
  {
    slug: "campaign-bold",
    title: "নির্বাচনী প্রচার — বোল্ড",
    titleEn: "Campaign — Bold",
    occasionType: "campaign",
    isActive: true,
    layoutConfig: {
      schemaVersion: 1,
      canvas: { width: 600, height: 800 },
      layoutFamily: "banner-diagonal",
      colorScheme: {
        background: "#FAF6EC",
        primary: "#14213D",
        secondary: "#D61F31",
        accent: "#F2B705",
        textOnPrimary: "#FFFFFF",
        textOnLight: "#14213D",
      },
      contrastPairs: [
        { fg: "textOnPrimary", bg: "primary", min: 4.5 },
        { fg: "textOnPrimary", bg: "secondary", min: 4.5 },
        { fg: "textOnLight", bg: "background", min: 4.5 },
        { fg: "secondary", bg: "background", min: 4.5 },
      ],
      layers: [
        { id: "base", type: "rect", x: 0, y: 0, w: 600, h: 800, fill: "$background" },
        { id: "band", type: "asset", asset: "campaign-bold/diagonal_band.svg", x: 0, y: 0, w: 600, h: 330 },
        { id: "head-block", type: "asset", asset: "campaign-bold/headline_block_slant.svg", x: 0, y: 488, w: 600, h: 212 },
      ],
      photoSlots: [
        { id: "center", shape: "rounded", x: 205, y: 30, w: 190, h: 250, z: 4, radius: 8, border: { width: 5, color: "$background" } },
        { id: "left", shape: "rounded", x: 30, y: 60, w: 160, h: 200, z: 3, radius: 8, border: { width: 5, color: "$background" } },
        { id: "right", shape: "rounded", x: 410, y: 60, w: 160, h: 200, z: 3, radius: 8, border: { width: 5, color: "$background" } },
        { id: "pairLeft", shape: "rounded", x: 80, y: 40, w: 200, h: 240, z: 3, radius: 8, border: { width: 5, color: "$background" } },
        { id: "pairRight", shape: "rounded", x: 320, y: 40, w: 200, h: 240, z: 3, radius: 8, border: { width: 5, color: "$background" } },
      ],
      photoAssignment: {
        "1": ["center"],
        "2": ["pairLeft", "pairRight"],
        "3": ["center", "left", "right"],
      },
      textSlots: [
        {
          id: "name",
          source: "name",
          x: 30,
          y: 348,
          w: 540,
          h: 64,
          fontFamily: "Hind Siliguri",
          fontWeight: 700,
          minFont: 22,
          maxFont: 48,
          maxLines: 1,
          lineHeight: 1.3,
          align: "center",
          valign: "middle",
          color: "$textOnLight",
        },
        {
          id: "designationOrgBody",
          source: "designationOrg",
          x: 30,
          y: 414,
          w: 540,
          h: 44,
          fontFamily: "Hind Siliguri",
          fontWeight: 600,
          minFont: 13,
          maxFont: 22,
          maxLines: 2,
          lineHeight: 1.3,
          align: "center",
          valign: "middle",
          color: "$secondary",
        },
        {
          id: "headline",
          source: "headline",
          x: 36,
          y: 520,
          w: 528,
          h: 124,
          fontFamily: "Hind Siliguri",
          fontWeight: 700,
          minFont: 30,
          maxFont: 80,
          maxLines: 3,
          lineHeight: 1.3,
          align: "center",
          valign: "middle",
          color: "$textOnPrimary",
        },
        {
          id: "subtext",
          source: "subtext",
          x: 48,
          y: 648,
          w: 504,
          h: 46,
          fontFamily: "Noto Sans Bengali",
          fontWeight: 500,
          minFont: 13,
          maxFont: 20,
          maxLines: 2,
          lineHeight: 1.5,
          align: "center",
          valign: "middle",
          color: "$textOnPrimary",
          truncate: true,
        },
      ],
      footer: { preset: "standard-v1", fill: "$primary", topRule: { height: 4, color: "$accent" } },
      decorations: [
        {
          key: "rays_burst",
          asset: "campaign-bold/rays_burst.svg",
          layer: "bg",
          opacity: 0.15,
          minIntensity: "high",
          placements: [{ x: 0, y: 0, w: 600, h: 330 }],
        },
        {
          key: "halftone_dots",
          asset: "campaign-bold/halftone_dots.svg",
          layer: "bg",
          opacity: 0.25,
          minIntensity: "medium",
          placements: [{ x: 0, y: 0, w: 600, h: 330 }],
        },
        {
          key: "chevron_stripe",
          asset: "campaign-bold/chevron_stripe.svg",
          layer: "mid",
          opacity: 1,
          minIntensity: "low",
          placements: [{ x: 0, y: 470, w: 600, h: 12 }],
        },
      ],
      aiAllowedDecorations: ["rays_burst", "halftone_dots", "chevron_stripe"],
      maxPhotos: 3,
    },
  },
];
